version: '2'

services:
  postgresql:
    image: 'postgres:12-alpine'
    env_file: ./.env
    environment:
      - POSTGRES_INITDB_ARGS=-E=UTF8
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./set-postgres-uid.sh:/set-postgres-uid.sh:ro
    entrypoint: ["/set-postgres-uid.sh"]
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-size: "100k"
  sonarqube:
    image: ${SQ_IMAGE}
    depends_on:
      - postgresql
    ports:
      - '${SQ_HTTP_PORT}:9000'
    environment:
      - SONAR_JDBC_USERNAME=${POSTGRES_USER}
      - SONAR_JDBC_PASSWORD=${POSTGRES_PASSWORD}
      - SONAR_JDBC_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    volumes:
      - ./data:/opt/sonarqube/data
      - ./logs:/opt/sonarqube/logs
      - ./extensions:/opt/sonarqube/extensions
    stop_grace_period: 3m
    restart: on-failure:1
    logging:
        driver: "json-file"
        options:
            max-size: "2m"
